### ISSUE TITLE
Bash completion build error

### ISSUE THREAD

**Issue by kchodorow** [google/bazel#113]
I'm getting (with --verbose_failures):

```
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=10682)... done.
......
INFO: Found 1 target...
INFO: From Building src/main/java/libbazel-core.jar (1192 files) [for host]:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
INFO: From Executing genrule //scripts:bash_completion:
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
/bin/bash: line 3: 13421 Aborted                 (core dumped) bazel-out/host/bin/src/bazel help completion 2> err.log >> bazel-out/local_linux-fastbuild/bin/scripts/bazel-complete.bash
ERROR: /home/kchodorow/gitroot/bazel/scripts/BUILD:7:1: Executing genrule //scripts:bash_completion failed: bash failed: error executing command 
  (cd /home/kchodorow/.cache/bazel/_bazel_kchodorow/732c1e8a78acec61831f6448799afba1/bazel && \
  exec env - \
  /bin/bash -c 'source tools/genrule/genrule-setup.sh; set +x; cat scripts/bazel-complete-template.bash > bazel-out/local_linux-fastbuild/bin/scripts/bazel-complete.bash
touch WORKSPACE err.log
trap "rm WORKSPACE err.log" EXIT
bazel-out/host/bin/src/bazel help completion 2>err.log >>bazel-out/local_linux-fastbuild/bin/scripts/bazel-complete.bash || { cat err.log; exit 1; }'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: bash failed: error executing command 
  (cd /home/kchodorow/.cache/bazel/_bazel_kchodorow/732c1e8a78acec61831f6448799afba1/bazel && \
  exec env - \
  /bin/bash -c 'source tools/genrule/genrule-setup.sh; set +x; cat scripts/bazel-complete-template.bash > bazel-out/local_linux-fastbuild/bin/scripts/bazel-complete.bash
touch WORKSPACE err.log
trap "rm WORKSPACE err.log" EXIT
bazel-out/host/bin/src/bazel help completion 2>err.log >>bazel-out/local_linux-fastbuild/bin/scripts/bazel-complete.bash || { cat err.log; exit 1; }'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //scripts:bash_completion failed to build
INFO: Elapsed time: 22.022s, Critical Path: 18.78s
```

**Comment by damienmg** [comment]
what ? Can you do "bazel help completion" with a bootstrapped version? It
was the error I was getting when the WORKSPACE file was not here. What
machine was it on?

**Comment by kchodorow** [comment]
```
$ bazel-bin/src/bazel help completion
BAZEL_COMMAND_LIST="build canonicalize-flags clean help doc_ext info analyze-profile query run shutdown test version"
BAZEL_INFO_KEYS="
workspace
install_base
output_base
execution_root
output_path
...
--noexperimental_external_repositories
--force_experimental_external_repositories
--noforce_experimental_external_repositories
"
```

**Comment by damienmg** [comment]
humm and out of a workspace?

Which distrib is it?

**Comment by kchodorow** [comment]
The latest code on Github (on my desktop).

**Comment by damienmg** [comment]
got it on my workstation. that's a regression

**Comment by damienmg** [comment]
btw there a set +x in that build that should be removed.

**Comment by damienmg** [comment]
Ok I traced back this problem to:
#9  0x000000000041c480 in blaze_util::Which(std::string const&) ()
#10 0x000000000041d376 in blaze::GetDefaultHostJavabase() ()

The thing is JAVA_HOME is undefined inside the spawn process so it is trying to find the JDK using the path leading to an exception because the path is empty. I'll send out a fix for both problems.
