### ISSUE TITLE
bazel crash with generated C++ file and up-level include references

### ISSUE THREAD

**Issue by janakdr** [google/bazel#152]
Reported by Austin in https://groups.google.com/d/topic/bazel-discuss/Q22UcwreK7Y/discussion :

I was playing around with building a QT application with bazel and ran into an interesting place where the error messages that Bazel returns could be improved.

The generated file contains a #include with .. in the path.

Generated file:
.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project/bazel-out/local_linux-fastbuild/genfiles/gui/moc_mainwindow.cc

First line:
#include "../../../../../../../../../local/bazel-project/gui/mainwindow.h"

Bazel then blows up with the following exception:  (line numbers may not match since I've been adding println statements to debug)

java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'Compiling gui/moc_mainwindow.cc' (CppCompile[[Artifact:[[/home/austin/.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project]bazel-out/host/internal]_middlemen/tools_Scpp_Cempty, Artifact:[[/home/austin/.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project]bazel-out/local_linux-fastbuild/genfiles]gui/moc_mainwindow.cc, Artifact:[[/home/austin/.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project]bazel-out/local_linux-fastbuild/internal]_middlemen/_S_Sgui_C_Utestcc0-cpp_compilation_prerequisites], unknown inputs -> [Artifact:[[/home/austin/.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project]bazel-out/local_linux-fastbuild/bin]gui/_objs/_testcc0/gui/moc_mainwindow.pic.o, Artifact:[[/home/austin/.cache/bazel/_bazel_austin/fdcadfdf1171aa4409009c2ab788d609/bazel-project]bazel-out/local_linux-fastbuild/bin]gui/_objs/_testcc0/gui/moc_mainwindow.pic.d]])' (requested by nodes 'ARTIFACT:gui/_objs/_testcc0/gui/moc_mainwindow.pic.o //gui:_testcc0 local_linux-fastbuild-b642fffe0fe3887467736a46479f9857')
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:713)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: /home/austin/local/bazel-project[source]: illegal root for /local/bazel-project/gui/mainwindow.h
        at com.google.devtools.build.lib.actions.Artifact.<init>(Artifact.java:148)
        at com.google.devtools.build.lib.actions.ArtifactFactory.createArtifact(ArtifactFactory.java:228)
        at com.google.devtools.build.lib.actions.ArtifactFactory.getArtifact(ArtifactFactory.java:208)
        at com.google.devtools.build.lib.actions.ArtifactFactory.getSourceArtifact(ArtifactFactory.java:117)
        at com.google.devtools.build.lib.actions.ArtifactFactory.resolveSourceArtifact(ArtifactFactory.java:254)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.populateActionInputs(CppCompileAction.java:873)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.updateActionInputs(CppCompileAction.java:789)
        at com.google.devtools.build.lib.rules.cpp.CppCompileAction.execute(CppCompileAction.java:1060)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:756)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:695)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:95)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:596)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:556)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:389)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:334)
        at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:153)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:674)
        ... 4 more

I'm willing to bet that the leading ../../ is confusing bazel.  Should a leading ../ be an error in DependencySet.java or CppCompileAction.populateActionInputs ?  That would produce a much better error and have saved a lot of debug time.

**Comment by janakdr** [comment]
https://bazel-review.googlesource.com/#/c/1211/2 sent out.
