### ISSUE TITLE
generate_workspace script fails with a link error on OS X

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#261]
It builds fine but gives this error at runtime:

```
INFO: Running command line: bazel-bin/src/main/java/com/google/devtools/build/workspace/generate_workspace '--bazel_project=/Users/erik/github/Master'
Exception in thread "main" java.lang.UnsatisfiedLinkError: no unix in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.devtools.build.lib.UnixJniLoader.loadJni(UnixJniLoader.java:25)
	at com.google.devtools.build.lib.unix.FilesystemUtils.<clinit>(FilesystemUtils.java:136)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.statInternal(UnixFileSystem.java:168)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.stat(UnixFileSystem.java:159)
	at com.google.devtools.build.lib.vfs.UnixFileSystem.getFileSize(UnixFileSystem.java:353)
	at com.google.devtools.build.lib.vfs.Path.getFileSize(Path.java:805)
	at com.google.devtools.build.lib.syntax.ParserInputSource.create(ParserInputSource.java:50)
	at com.google.devtools.build.workspace.Resolver.parse(Resolver.java:69)
	at com.google.devtools.build.workspace.GenerateWorkspace.generateFromWorkspace(GenerateWorkspace.java:76)
	at com.google.devtools.build.workspace.GenerateWorkspace.main(GenerateWorkspace.java:50)
```

Looks like it's making unix-specific assumptions about the filesystem

**Comment by kchodorow** [comment]
That was fast :)

It actually _is_ trying to use the libunix.dylib we generate on OS X, but obviously isn't finding it.

**Comment by promiseofcake** [comment]
Still seeing similar behavior on 0.4.5 and 0.5.1.

**Comment by kchodorow** [comment]
Please use https://github.com/bazelbuild/migration-tooling instead. (We're working on updating the documentation.)

**Comment by promiseofcake** [comment]
@kchodorow Thank you!
