### ISSUE TITLE
NoClassDefFoundError from Error Prone when enabling StringEquality check

### ISSUE THREAD

**Issue by ekuefler** [google/bazel#265]
If (and only if) I pass `--javacopt="-Xep:StringEquality:ERROR"` to bazel, I get the following error trying to build anything:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/checkerframework/dataflow/analysis/TransferFunction
	at com.google.errorprone.bugpatterns.StringEquality.<init>(StringEquality.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:58)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:54)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.errorprone.scanner.ErrorProneScanner.<init>(ErrorProneScanner.java:185)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:67)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:38)
	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.init(ErrorPronePlugin.java:158)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.<init>(BlazeJavaCompiler.java:48)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler$1.make(BlazeJavaCompiler.java:67)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler$1.make(BlazeJavaCompiler.java:64)
	at com.sun.tools.javac.util.Context.get(Context.java:150)
	at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:94)
	at com.sun.tools.javac.main.Main.compile(Main.java:242)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:125)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:118)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:58)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:117)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:40)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:86)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.checkerframework.dataflow.analysis.TransferFunction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

**Comment by ekuefler** [comment]
I also get NoClassDefFound when I pass `--javacopt="-Xep:MalformedFormatString:ERROR"`, with this stack trace:
```
Exception in thread "main" java.lang.NoClassDefFoundError: edu/umd/cs/findbugs/formatStringChecker/ExtraFormatArgumentsException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:58)
	at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:54)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.errorprone.scanner.ErrorProneScanner.<init>(ErrorProneScanner.java:185)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:67)
	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:38)
	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.init(ErrorPronePlugin.java:158)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.<init>(BlazeJavaCompiler.java:48)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler$1.make(BlazeJavaCompiler.java:67)
	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler$1.make(BlazeJavaCompiler.java:64)
	at com.sun.tools.javac.util.Context.get(Context.java:150)
	at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:94)
	at com.sun.tools.javac.main.Main.compile(Main.java:242)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:125)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:118)
	at com.google.devtools.build.buildjar.javac.JavacRunnerImpl.invokeJavac(JavacRunnerImpl.java:44)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:58)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.internalCompileJavaLibrary(AbstractJavaBuilder.java:117)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder.access$000(AbstractJavaBuilder.java:40)
	at com.google.devtools.build.buildjar.AbstractJavaBuilder$1.run(AbstractJavaBuilder.java:86)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: edu.umd.cs.findbugs.formatStringChecker.ExtraFormatArgumentsException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```

The rest of the checks are all either fine or have the problem from #266

**Comment by cushon** [comment]
Thanks, looks like bazel isn't including error prone's transitive dependencies. I'm working on a fix.
