### ISSUE TITLE
Bazel crashed with a NPE

### ISSUE THREAD

**Issue by korfuri** [google/bazel#351]
Hi,

I'm not sure how to provide more info, but here is my crash log:

````
ERROR: /home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/external/protobuf/BUILD:53:1: C++ compilation of rule '@protobuf//:protobuf' failed: gcc-4.8 failed: error executing command /usr/bin/gcc-4.8 -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -iquote . -iquote ... (remaining 27 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15; also encountered an error while attempting to retrieve output.
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'ARTIFACT:gtest/gtest-all.cc @gtest//gtest:fused 328c70e1efb1ded482c8167e886cd977' (requested by nodes 'ACTION_EXECUTION:action 'Compiling gtest/gtest-all.cc' (CppCompile[[Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/host/internal]_middlemen/tools_Sbazel-travis_Scustom_Ucrosstool_Cempty, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/genfiles]gtest/gtest-all.cc, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/internal]_middlemen/@gtest_S_Sgtest_Cgtest-cpp_compilation_prerequisites], unknown inputs -> [Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/bin]external/gtest/gtest/_objs/gtest/gtest/gtest-all.pic.o, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/bin]external/gtest/gtest/_objs/gtest/gtest/gtest-all.pic.d]])')
INFO: Elapsed time: 13.749s, Critical Path: 1.28s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ARTIFACT:gtest/gtest-all.cc @gtest//gtest:fused 328c70e1efb1ded482c8167e886cd977' (requested by nodes 'ACTION_EXECUTION:action 'Compiling gtest/gtest-all.cc' (CppCompile[[Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/host/internal]_middlemen/tools_Sbazel-travis_Scustom_Ucrosstool_Cempty, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/genfiles]gtest/gtest-all.cc, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/internal]_middlemen/@gtest_S_Sgtest_Cgtest-cpp_compilation_prerequisites], unknown inputs -> [Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/bin]external/gtest/gtest/_objs/gtest/gtest/gtest-all.pic.o, Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/bin]external/gtest/gtest/_objs/gtest/gtest/gtest-all.pic.d]])')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:745)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Value ConfiguredTargetValue: ConfiguredTarget(@gtest//gtest:fused, 328c70e1efb1ded482c8167e886cd977), actions: [action 'Executing genrule @gtest//gtest:fused' (Genrule[[Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-death-test.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-filepath.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-port.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-printers.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-test-part.cc, Artifact:[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b[source]]external/gtest/gtest/gtest-typed-test.cc, Artifact:[/home/travis/build/korfuri/client_cpp/bazel/base_workspace[source]]tools/genrule/genrule-setup.sh] -> [Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/genfiles]external/gtest/gtest/gtest-all.cc]])] does not contain generating action of Artifact:[[/home/travis/.cache/bazel/_bazel_travis/8118365963b10f87b4ed7c478e261f8b/client_cpp]bazel-out/local_linux-fastbuild/genfiles]gtest/gtest-all.cc
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.extractActionFromArtifact(ArtifactFunction.java:209)
	at com.google.devtools.build.lib.skyframe.ArtifactFunction.compute(ArtifactFunction.java:68)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:709)
	... 4 more
````

Bazel was built at current HEAD, 49543429f56cfe9c90562a1e9f9c66a9eabb5385. Here's the full log that will also point you to the workspace and build files used: https://travis-ci.org/korfuri/client_cpp/builds/73315413

The same build with Bazel at d93990f passes. See e.g. https://travis-ci.org/korfuri/client_cpp/builds/73316483 (the only difference is that I explicitly sync at d93990f before building).

I'm happy to provide more logs if you tell me what you need.

**Comment by damienmg** [comment]
Reproduced. Trying to locate the culprit change.

**Comment by damienmg** [comment]
It also crashes using d93990f on my workstation

**Comment by damienmg** [comment]
And the winner is 4a89a9b229b5eb80b86b90b61a268b4004c0bd70!

**Comment by lberki** [comment]
I have a minimal reproduction with two genrules. Digging.

**Comment by lberki** [comment]
I have a patch.

**Comment by lberki** [comment]
Patch submitted for code review. ETA is tomorrow morning CEST.

In the meantime, it's a single-line change: it replaces this line in ConfiguredTargetFactory#getOutputArtifact():

```java
PathFragment rootRelativePath = Util.getWorkspaceRelativePath(outputFile);
```

With this:

```java
PathFragment rootRelativePath =
        outputFile.getLabel().getPackageIdentifier().getPathFragment().getRelative(
            outputFile.getLabel().getName());
```

**Comment by damienmg** [comment]
ETA is less than an hour, I'll export when your fix is in.
