### ISSUE TITLE
"baseName must not contain a slash: '/

### ISSUE THREAD

**Issue by cflewis** [google/bazel#367]
Using the Dockerfile image of `FROM google/debian:wheezy` and installing Java 8, I get this error when I try to run `blaze build`. It's super non-descript. What's the baseName? What does it do? Why can it not have a `/` in it? Any ideas?

I am not sync'd to HEAD due to #359 .

INFO     2015-08-09 23:43:24,140 containers.py:282] 
unexpected pipe read status: Connection refused
Server presumed dead. Now printing '/root/.cache/bazel/_bazel_root/6666cd76f96956469e7be39d750cc7d9/server/jvm.out':

INFO     2015-08-09 23:43:24,140 containers.py:282] Aug 09, 2015 11:43:10 PM com.google.devtools.build.lib.analysis.BlazeVersionInfo logVersionInfo
INFO: Blaze version info: Build label: head (@ecd4ec4)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Sun Aug 9 23:26:01 2015 (1439162761)
Build timestamp: 1439162761
Build timestamp as int: 1439162761
Aug 09, 2015 11:43:10 PM com.google.devtools.build.lib.runtime.BlazeRuntime main
INFO: Starting Blaze server with args [--max_idle_secs, 10800, --install_base=/root/.cache/bazel/_bazel_root/install/3d61be13abbadd3d74789671a1266ee5, --output_base=/root/.cache/bazel/_bazel_root/6666cd76f96956469e7be39d750cc7d9, --workspace_directory=/, --nofatal_event_bus_exceptions, --option_sources=]
java.lang.IllegalArgumentException: baseName must not contain a slash: '/'
	at com.google.devtools.build.lib.vfs.FileSystemUtils.checkBaseName(FileSystemUtils.java:79)
	at com.google.devtools.build.lib.vfs.Path.getChild(Path.java:575)
	at com.google.devtools.build.lib.analysis.BlazeDirectories.<init>(BlazeDirectories.java:76)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1488)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:1339)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1312)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:1103)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:49)
Aug 09, 2015 11:43:10 PM com.google.devtools.build.lib.runtime.BugReport printThrowableTo
SEVERE: Blaze crashed
java.lang.IllegalArgumentException: baseName must not contain a slash: '/'
	at com.google.devtools.build.lib.vfs.FileSystemUtils.checkBaseName(FileSystemUtils.java:79)
	at com.google.devtools.build.lib.vfs.Path.getChild(Path.java:575)
	at com.google.devtools.build.lib.analysis.BlazeDirectories.<init>(BlazeDirectories.java:76)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.newRuntime(BlazeRuntime.java:1488)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.createBlazeRPCServer(BlazeRuntime.java:1339)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1312)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:1103)
	at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:49)

**Comment by cflewis** [comment]
My Dockerfile is at https://github.com/cflewis/wordcount/blob/eb66dbc9882ca43a643d1b4eee3e40721f0079aa/Dockerfile

**Comment by cflewis** [comment]
Note this doesn't happen with the base image `FROM gcr.io/google_appengine/java-compat`

**Comment by kchodorow** [comment]
It looks like this was caused by the --workspace_directory=/.

**Comment by damienmg** [comment]
I was about to assign ot to you due to https://github.com/google/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/BlazeDirectories.java#L76 :)
