### ISSUE TITLE
Linux sandboxing and relative symbolic links

### ISSUE THREAD

**Issue by pedropaco** [google/bazel#400]
I'm on Ubuntu 14.04, and per the instructions installed open jdk 7.  This has a relative symbolic link to java-atk-wrapper.jar:

```
java-atk-wrapper.jar -> ../../../../../../share/java/java-atk-wrapper.jar
```
On running compile.sh, attempting to follow this results in a RuntimException.
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ACTION_EXECUTION:action 'GenProtoSrcJar (... extremely long debug string omitted )
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:762)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$2.run(AbstractQueueVisitor.java:436)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: /home/asdf/.cache/bazel/_bazel_asdf/7134f4c09603fe60c80b65c218f4afb1/share/java/java-atk-wrapper.jar does not exist
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.validateAndAddMount(LinuxSandboxedStrategy.java:257)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.getMounts(LinuxSandboxedStrategy.java:233)
	at com.google.devtools.build.lib.sandbox.LinuxSandboxedStrategy.exec(LinuxSandboxedStrategy.java:121)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:225)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:233)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:769)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:708)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$900(SkyframeActionExecutor.java:98)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:609)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:569)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:365)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:169)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:726)
	... 4 more
```

**Comment by philwo** [comment]
Thanks for reporting this issue. I have a fix for this and it will be part of the next push.

**Comment by philwo** [comment]
Preliminary fix that unbreaks the bootstrap (compile.sh) is being pushed to the Bazel repo today, a more complete "let's solve this once and for all" solution will follow. :)

**Comment by pedropaco** [comment]
Verified on my end.  Thanks for the quick turnaround. :)
