### ISSUE TITLE
Segfault on bazel init

### ISSUE THREAD

**Issue by markchadwick** [google/bazel#68]
Compiled bazel from source using `./compile.sh` -- resulting binary segfaults moments after starting.

Ubuntu 12.04.5 LTS
java-8-oracle (from the PPA suggested here: http://bazel.io/docs/install.html)
libc6 2.15-0ubuntu10.11

To reproduce:
```
$ git clone https://github.com/google/bazel
$ cd bazel
$ ./compile.sh
Compiling Java stubs for protocol buffers...
Compiling Bazel Java code...
Extracting helper classes for Bazel Java...
Creating libblaze.jar...
Compiling SingleJar tool code...
Extracting helper classes for SingleJar tool...
Creating SingleJar_deploy.jar...
Compiling JavaBuilder tool code...
Extracting helper classes for JavaBuilder tool...
Creating JavaBuilder_deploy.jar...
Compiling client .cc files...
Linking client...
Compiling ijar .cc files...
Linking ijar...
Compiling JNI libraries...
Linking libunix.so...
Compiling build-runfiles...
Compiling process-wrapper...
Compiling sandbox...
Creating Bazel self-extracting archive...
Creating objc helper tools...
Compiling actoolzip code...
Extracting helper classes for actoolzip...
Creating precomp_actoolzip_deploy.jar...
Compiling ibtoolzip code...
Extracting helper classes for ibtoolzip...
Creating precomp_ibtoolzip_deploy.jar...
Compiling momczip code...
Extracting helper classes for momczip...
Creating precomp_momczip_deploy.jar...
Compiling bundlemerge code...
Extracting helper classes for bundlemerge...
Creating precomp_bundlemerge_deploy.jar...
Compiling plmerge code...
Extracting helper classes for plmerge...
Creating precomp_plmerge_deploy.jar...
Compiling xcodegen code...
Extracting helper classes for xcodegen...
Creating precomp_xcodegen_deploy.jar...
Build successful! Binary is here: (...)/bazel/output/bazel
$ ./output/bazel 
Extracting Bazel installation...
Segmentation fault (core dumped)
```

Inspecting the core:
```
$gdb ./output/bazel core 
...
warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fffe23fe000
Core was generated by `./output/bazel'.
Program terminated with signal 11, Segmentation fault.

(gdb) thread apply all where
Thread 1 (Thread 0x7f51dc60f740 (LWP 26482)):
#0  0x00007f51db7f7ec5 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f51dc1bb842 in std::string::_Rep::_M_clone(std::allocator<char> const&, unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f51dc1bbf5c in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x0000000000404d86 in blaze::BlazeStartupOptions::GetJvm (this=0x1383100)
    at src/main/cpp/blaze_startup_options.cc:136
#4  0x000000000040f017 in blaze::VerifyJavaVersionAndGetJvm () at src/main/cpp/blaze.cc:443
#5  0x000000000040f434 in blaze::StartServer (socket=6) at src/main/cpp/blaze.cc:489
#6  0x000000000040fd47 in blaze::ConnectToServer (start=true) at src/main/cpp/blaze.cc:637
#7  0x0000000000411f87 in blaze::SendServerRequest () at src/main/cpp/blaze.cc:1150
#8  0x00000000004140be in blaze::main (argc=1, argv=0x7fffe22c7298) at src/main/cpp/blaze.cc:1687
#9  0x000000000041416b in main (argc=1, argv=0x7fffe22c7298) at src/main/cpp/blaze.cc:1694
```

**Comment by ulfjack** [comment]
The last LTS has a broken gcc. I have a fix for that in the circleci branch.

**Comment by damienmg** [comment]
Kristina got into the same problem with our builds on TravisCI.

**Comment by lberki** [comment]
Assigning to ulfjack since he already has a fix.

**Comment by ulfjack** [comment]
I won't get to this before the middle of next week.

**Comment by hanwen** [comment]
Ulf, ping?
