### ISSUE TITLE
skylark: cannot reference other label as output

### ISSUE THREAD

**Issue by hanwen** [google/bazel#91]
diff --git a/tools/build_rules/genproto.bzl b/tools/build_rules/genproto.bzl
index f479027..1d1a7e5 100644
--- a/tools/build_rules/genproto.bzl
+++ b/tools/build_rules/genproto.bzl
@@ -92,5 +92,8 @@ genproto = rule(genproto_impl,
            single_file=True,
            ),
    },
-   outputs = {"java": "lib%{name}.jar"},
+   outputs = {
+          "java": "lib%{name}.jar",
+          "bla": "%{src}.out",
+   },
 )

java.lang.RuntimeException: Unrecoverable error while evaluating node 'PACKAGE:src/main/protobuf' (requested by nodes 'RECURSIVE_PKG:[/home/hanwen/vc/bazel]/[src/main/protobuf]')
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:918)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Don't know how to handle src : label
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.attributeValues(ImplicitOutputsFunction.java:318)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.access$000(ImplicitOutputsFunction.java:53)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$1.get(ImplicitOutputsFunction.java:167)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:395)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction.substitutePlaceholderIntoTemplate(ImplicitOutputsFunction.java:368)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$3.getImplicitOutputs(ImplicitOutputsFunction.java:212)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunctionWithMap.calculateOutputs(ImplicitOutputsFunction.java:130)
	at com.google.devtools.build.lib.packages.ImplicitOutputsFunction$SkylarkImplicitOutputsFunction.getImplicitOutputs(ImplicitOutputsFunction.java:65)
	at com.google.devtools.build.lib.packages.Rule.populateImplicitOutputFiles(Rule.java:524)
	at com.google.devtools.build.lib.packages.Rule.populateOutputFiles(Rule.java:491)
	at com.google.devtools.build.lib.packages.RuleClass.createRuleCommon(RuleClass.java:1120)
	at com.google.devtools.build.lib.packages.RuleClass.createRuleWithLabel(RuleClass.java:1111)
	at com.google.devtools.build.lib.packages.RuleFactory.createRule(RuleFactory.java:102)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:133)
	at com.google.devtools.build.lib.packages.RuleFactory.createAndAddRule(RuleFactory.java:142)
	at com.google.devtools.build.lib.rules.SkylarkRuleClassFunctions$RuleFunction.call(SkylarkRuleClassFunctions.java:292)
	at com.google.devtools.build.lib.syntax.FuncallExpression.eval(FuncallExpression.java:517)
	at com.google.devtools.build.lib.syntax.ListComprehension.evalLists(ListComprehension.java:115)
	at com.google.devtools.build.lib.syntax.ListComprehension.eval(ListComprehension.java:60)
	at com.google.devtools.build.lib.syntax.ExpressionStatement.exec(ExpressionStatement.java:39)
	at com.google.devtools.build.lib.syntax.BuildFileAST.exec(BuildFileAST.java:136)
	at com.google.devtools.build.lib.packages.PackageFactory.evaluateBuildFile(PackageFactory.java:1218)
	at com.google.devtools.build.lib.packages.PackageFactory.createPackageFromPreprocessingResult(PackageFactory.java:958)
	at com.google.devtools.build.lib.skyframe.PackageFunction.loadPackage(PackageFunction.java:736)
	at com.google.devtools.build.lib.skyframe.PackageFunction.compute(PackageFunction.java:469)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:879)

**Comment by laurentlb** [comment]
Fixed.
