### ISSUE TITLE
NPE in stamping support

### ISSUE THREAD

**Issue by ulfjack** [google/bazel#98]
So I dig the code a little bit, after reading CcLibrary.java's code, I
guess "linkstamp" is the option to specify some genrule target to
create some ephemeral file to create link stamp, but then I got this
exception:

Unhandled exception thrown during build; message: Unrecoverable error
while evaluating node 'CONFIGURED_TARGET://examples:hello
local_linux-fastbuild-5a18746e823ad64d88efb5add1d017bc' (requested by
nodes )
INFO: Elapsed time: 0.441s
java.lang.RuntimeException: Unrecoverable error while evaluating node
'CONFIGURED_TARGET://examples:hello
local_linux-fastbuild-5a18746e823ad64d88efb5add1d017bc' (requested by
nodes )
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:918)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$1.run(AbstractQueueVisitor.java:346)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.google.devtools.build.lib.analysis.CachingAnalysisEnvironment.getBuildInfo(CachingAnalysisEnvironment.java:293)
        at com.google.devtools.build.lib.rules.cpp.CppLinkAction$Builder.build(CppLinkAction.java:619)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:228)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:151)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:66)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:236)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:163)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:400)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:482)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:173)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:879)
        ... 4 more

**Comment by hanwen** [comment]
we need a repro scenario. Please reopen if you have one.
